name: Gitee repos mirror periodic job
on:
  push:
  #每天北京时间早上七点运行
  #schedule:  
  #- cron: '0 23 * * *'
env:
  PYTHON_VER: 3.8

jobs:

  # 第一个任务递归获取NCS中所有repo的url
  get-repo-list:
    name: Get all repos and sbumodules name in NCS
    runs-on: ubuntu-latest
    # outputs:
    #   ncs-repo-list: ${{ steps. }}
    steps:
    - name: Use Python version ${{ env.PYTHON_VER }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VER }}
    - name: Get the NCS
      run: |
        sudo apt update -y
        sudo apt upgrade -y
        sudo apt install -y --no-install-recommends git
        pip3 install --user west
        export PATH=~/.local/bin:"$PATH"
        pwd
        west init -m https://github.com/nrfconnect/sdk-nrf -mr master ncs
        pwd
        west update